name: dart_extensions
description: basic extension methods and useful functions for Dart
version: 0.0.1
publish_to:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  test: ^1.24.4
  convert: ^3.1.1
  intl: ^0.19.0